-- Ordem inversa à de criação para evitar erro por dependência

DROP TABLE MC_SGV_VISUALIZACAO_VIDEO CASCADE CONSTRAINTS;
DROP TABLE MC_SGV_PRODUTO_VIDEO CASCADE CONSTRAINTS;
DROP TABLE MC_SGV_SAC CASCADE CONSTRAINTS;

DROP TABLE MC_END_FUNC CASCADE CONSTRAINTS;
DROP TABLE MC_FUNCIONARIO CASCADE CONSTRAINTS;
DROP TABLE MC_DEPTP CASCADE CONSTRAINTS;

DROP TABLE MC_END_CLI CASCADE CONSTRAINTS;
DROP TABLE MC_CLI_FISICA CASCADE CONSTRAINTS;
DROP TABLE MC_CLI_JURIDICA CASCADE CONSTRAINTS;
DROP TABLE MC_CLIENTE CASCADE CONSTRAINTS;

DROP TABLE MC_PRODUTO CASCADE CONSTRAINTS;
DROP TABLE MC_CATEGORIA_PROD CASCADE CONSTRAINTS;

DROP TABLE MC_LOGRADOURO CASCADE CONSTRAINTS;
DROP TABLE MC_BAIRRO CASCADE CONSTRAINTS;
DROP TABLE MC_CIDADE CASCADE CONSTRAINTS;
DROP TABLE MC_ESTADO CASCADE CONSTRAINTS;
