-- Tabela de estados
CREATE TABLE MC_ESTADO (
    SG_ESTADO CHAR(2) PRIMARY KEY,
    NM_ESTADO VARCHAR2(40)
);

-- Tabela de cidades
CREATE TABLE MC_CIDADE (
    CD_CIDADE NUMBER(10) PRIMARY KEY,
    NM_CIDADE VARCHAR2(60),
    SG_ESTADO CHAR(2),
    FOREIGN KEY (SG_ESTADO) REFERENCES MC_ESTADO(SG_ESTADO)
);

-- Tabela de bairros
CREATE TABLE MC_BAIRRO (
    CD_BAIRRO NUMBER(10) PRIMARY KEY,
    NM_BAIRRO VARCHAR2(50),
    CD_CIDADE NUMBER(10),
    FOREIGN KEY (CD_CIDADE) REFERENCES MC_CIDADE(CD_CIDADE)
);

-- Tabela de logradouro
CREATE TABLE MC_LOGRADOURO (
    CD_LOGRADOURO NUMBER(10) PRIMARY KEY,
    NM_LOGRADOURO VARCHAR2(100),
    NM_COMPLEMENTO VARCHAR2(100),
    CD_BAIRRO NUMBER(10),
    FOREIGN KEY (CD_BAIRRO) REFERENCES MC_BAIRRO(CD_BAIRRO)
);

-- Tabela de departamentos
CREATE TABLE MC_DEPTP (
    CD_DEPTO NUMBER(5) PRIMARY KEY,
    NM_DEPTO VARCHAR2(50)
);

-- Tabela de funcionários
CREATE TABLE MC_FUNCIONARIO (
    CD_FUNCIONARIO NUMBER(10) PRIMARY KEY,
    NM_FUNCIONARIO VARCHAR2(100),
    NR_CPF VARCHAR2(11),
    DT_NASCIMENTO DATE,
    DT_ADMISSAO DATE,
    CD_DEPTO NUMBER(5),
    FOREIGN KEY (CD_DEPTO) REFERENCES MC_DEPTP(CD_DEPTO)
);

-- Endereço do funcionário
CREATE TABLE MC_END_FUNC (
    CD_FUNCIONARIO NUMBER(10),
    CD_LOGRADOURO NUMBER(10),
    NR_END_FUNC VARCHAR2(10),
    DS_COMPLEMENTO VARCHAR2(100),
    PRIMARY KEY (CD_FUNCIONARIO, CD_LOGRADOURO),
    FOREIGN KEY (CD_FUNCIONARIO) REFERENCES MC_FUNCIONARIO(CD_FUNCIONARIO),
    FOREIGN KEY (CD_LOGRADOURO) REFERENCES MC_LOGRADOURO(CD_LOGRADOURO)
);

-- Tabela de clientes
CREATE TABLE MC_CLIENTE (
    NR_CLIENTE NUMBER(10) PRIMARY KEY,
    NM_CLIENTE VARCHAR2(100),
    DS_EMAIL VARCHAR2(100),
    NR_TELEFONE VARCHAR2(15)
);

-- Cliente pessoa física
CREATE TABLE MC_CLI_FISICA (
    NR_CLIENTE NUMBER(10) PRIMARY KEY,
    NR_CPF VARCHAR2(11),
    DT_NASCIMENTO DATE,
    FOREIGN KEY (NR_CLIENTE) REFERENCES MC_CLIENTE(NR_CLIENTE)
);

-- Cliente pessoa jurídica
CREATE TABLE MC_CLI_JURIDICA (
    NR_CLIENTE NUMBER(10) PRIMARY KEY,
    NR_CNPJ VARCHAR2(14),
    NM_RAZAO_SOCIAL VARCHAR2(100),
    FOREIGN KEY (NR_CLIENTE) REFERENCES MC_CLIENTE(NR_CLIENTE)
);

-- Endereço do cliente
CREATE TABLE MC_END_CLI (
    NR_CLIENTE NUMBER(10),
    CD_LOGRADOURO NUMBER(10),
    NR_END_CLI VARCHAR2(10),
    DS_COMPLEMENTO VARCHAR2(100),
    PRIMARY KEY (NR_CLIENTE, CD_LOGRADOURO),
    FOREIGN KEY (NR_CLIENTE) REFERENCES MC_CLIENTE(NR_CLIENTE),
    FOREIGN KEY (CD_LOGRADOURO) REFERENCES MC_LOGRADOURO(CD_LOGRADOURO)
);

-- Tabela de categorias de produto
CREATE TABLE MC_CATEGORIA_PROD (
    CD_CATEGORIA NUMBER(5) PRIMARY KEY,
    DS_CATEGORIA VARCHAR2(50)
);

-- Tabela de produtos
CREATE TABLE MC_PRODUTO (
    CD_PRODUTO NUMBER(10) PRIMARY KEY,
    NM_PRODUTO VARCHAR2(100),
    DS_PRODUTO VARCHAR2(255),
    VL_PRODUTO NUMBER(10,2),
    CD_CATEGORIA NUMBER(5),
    FOREIGN KEY (CD_CATEGORIA) REFERENCES MC_CATEGORIA_PROD(CD_CATEGORIA)
);

-- Tabela de associação produto-vídeo
CREATE TABLE MC_SGV_PRODUTO_VIDEO (
    CD_PRODUTO NUMBER(10),
    NR_SEQUENCIA NUMBER(5),
    URL_VIDEO VARCHAR2(255),
    PRIMARY KEY (CD_PRODUTO, NR_SEQUENCIA),
    FOREIGN KEY (CD_PRODUTO) REFERENCES MC_PRODUTO(CD_PRODUTO)
);

-- Tabela de visualização de vídeos
CREATE TABLE MC_SGV_VISUALIZACAO_VIDEO (
    CD_VISUALIZACAO NUMBER(10) PRIMARY KEY,
    NR_CLIENTE NUMBER(10),
    CD_PRODUTO NUMBER(10),
    NR_SEQUENCIA NUMBER(5),
    DT_VISUALIZACAO DATE,
    TEMPO_VISUALIZADO NUMBER(5),
    FOREIGN KEY (NR_CLIENTE) REFERENCES MC_CLIENTE(NR_CLIENTE),
    FOREIGN KEY (CD_PRODUTO, NR_SEQUENCIA) REFERENCES MC_SGV_PRODUTO_VIDEO(CD_PRODUTO, NR_SEQUENCIA)
);

-- Tabela de atendimentos SAC
CREATE TABLE MC_SGV_SAC (
    CD_SAC NUMBER(10) PRIMARY KEY,
    NR_CLIENTE NUMBER(10),
    CD_FUNCIONARIO NUMBER(10),
    CD_PRODUTO NUMBER(10),
    DS_DUVIDA VARCHAR2(500),
    DS_RESPOSTA VARCHAR2(500),
    DT_ATENDIMENTO DATE,
    FOREIGN KEY (NR_CLIENTE) REFERENCES MC_CLIENTE(NR_CLIENTE),
    FOREIGN KEY (CD_FUNCIONARIO) REFERENCES MC_FUNCIONARIO(CD_FUNCIONARIO),
    FOREIGN KEY (CD_PRODUTO) REFERENCES MC_PRODUTO(CD_PRODUTO)
);
